name: CI/CD Pipeline for Node.js App with Docker

on:
  push:
    branches:
      - main  # Trigger workflow when code is pushed to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install


    # Step 4: Build Docker image
    - name: Build Docker image
      run: docker build -t meetlakhani99/my-node-demo .

    # Step 5: Log in to DockerHub
    - name: Log in to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    # Step 6: Tag and push Docker image to DockerHub
    - name: Push Docker image to DockerHub
      run: |
        docker tag meetlakhani99/my-node-demo meetlakhani99/my-node-demo:latest
        docker push meetlakhani99/my-node-demo:latest
